version: "2.4"

services:
  mysql-service:
    image: mysql
    container_name: mysql-db
    ports:
      - "3306:3306"
    volumes:
      - database_data:/var/lib/mysql
    environment:
        MYSQL_ROOT_PASSWORD: root

volumes:
  database_data:
